site_name: Video-on-Demand (AWS/Akamai)
site_url: https://wruppelx.github.io/mvs-aws-exercise
repo_url: https://github.com/wruppelx/mvs-aws-exercise
edit_uri: ""
theme:
  name: material
  language: de
  features:
    - toc.integrate
    - navigation.top
    - navigation.footer
    - content.code.copy
  logo: assets/logo_hsrm_weiss.svg
  favicon: assets/favicon.png
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Umschalten zu Lightmode
      primary: red
      accent: red

    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Umschalten zu Darkmode
      primary: red
      accent: red

markdown_extensions:
  - admonition
  - tables
  - attr_list
  - md_in_html
  - footnotes

plugins:
  - search:
      lang: de

nav:
  - Übersicht: index.md
  - Einleitung: einleitung.md
  - Versuch 1:
    - Einführung Versuch 1: versuch1/01-einfuehrung.md
    - AWS S3: versuch1/02-S3.md
    - AWS MediaConvert: versuch1/03-transcoder.md
    - Download: versuch1/04-download.md
    - Fazit: versuch1/05-fazit.md
    - Troubleshooting: versuch1/06-troubleshooting.md
  - Versuch 2:
    - Einführung Versuch 2: versuch2/01-einfuehrung.md
    - Property: versuch2/02-property.md
    - Netstorage: versuch2/03-netstorage.md
    - Inhalte Abrufen: versuch2/04-inhalte_abrufen.md
    - Fazit: versuch2/05-fazit.md
  - Versuch 3:
    - Einführung Versuch 3: versuch3/01-einfuehrung.md
    - S3 Vorbereitungen: versuch3/02-s3_vorbereitungen.md
    - SNS: versuch3/03-sns.md
    - Lambda: versuch3/04-lambda.md
    - Testen: versuch3/05-testen.md
    - Fazit: versuch3/06-fazit.md
    - Troubleshooting: versuch3/07-troubleshooting.md
  - Versuch 4:
    - Einführung Versuch 4: versuch4/01-einfuehrung.md
    - CloudShell: versuch4/02-cloudshell.md
    - Python SDK: versuch4/03-python_sdk.md
    - Fazit: versuch4/04-fazit.md
    - Troubleshooting: versuch4/05-troubleshooting.md